### ISSUE TITLE
Missing port on QRCode

### ISSUE THREAD

**Issue by VinceGel** [patrickhener/dart-o-mat-3000#1]
When we launch Dart-o-mat-3000 and go to webpage http://ip:5000/game a QRCode appears but the reported address is missing port number.

1 - Launch Dart-0-mat-3000
2 - go to website http://ip:5000/game
3 - scan the QRCode link to http://ip/game/...

Server is installed on a Macbook Pro (Python 3.7 installed through Brew) and also on a Raspberry  (Latest Raspbian version + Python 3.6)
I read QRCode from my cellphone (Oneplus 5T with latest OS)

**Comment by patrickhener** [comment]
With the latest commit and Version v0.9.9.2 Pre-release this issue is fixed.
Now you can choose wether your production server is ssl or not. Also if port 80 is chosen it will be left out of the url. Otherwise url will be constructed like ip:port.
