### ISSUE TITLE
Link Issue on QR CODE #2

### ISSUE THREAD

**Issue by VinceGel** [patrickhener/dart-o-mat-3000#2]
Dart-o-mat-3000 release 0.9.9.2
Running on a mac with Mac OsX 10.11
Python 3.7.3 installed through Brew
Mac Ip 192.168.1.17
config.py update: IPADDR = '192.168.1.37' / IFACE = '192.168.1.37'

When I run ./run.py it suggest me to connect to http://192.168.1.37:5000
I must update this link to http://192.168.1.37:5000/game/ to have QR Code you will find this webpage here:
[Setup_Page.zip](https://github.com/patrickhener/dart-o-mat-3000/files/3192771/Setup_Page.zip)
A snapshot of this picture
![QRCode_issue](https://user-images.githubusercontent.com/34207613/57950713-55e00000-78e8-11e9-9683-95960b1c3798.png)

The QRCode bring my Android phone (Oneplus 5T with latest OS Version) to http://192.168.1.37:5000. Here is the copy of the webpage :
[QRCodeLink.zip](https://github.com/patrickhener/dart-o-mat-3000/files/3192772/QRCodeLink.zip)

**Comment by patrickhener** [comment]
Hi there and thank you for reporting. You were totally right with the QR Code. It was a typo of mine when constructing the URL. I fixed this.
As of the ./run.py suggesting you to connect to http://192.168.1.37:5000 this is perfectly normal. The development server will just give you output on which interface and port it was bound and not where to find the entry point of the application.
Best regards,
Patrick
